//------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
using Terminal.Gui;
using Terminal.Gui.Views;

namespace ServerManager.Dialogs;

public partial class ChangeHostname
{
	public ChangeHostname()
	{
		InitializeComponent();
		renameButton.Accepted += RenameButtonAccepted;
		cancelButton.Accepted += (s, e) => this.RequestStop();
	}

	private void RenameButtonAccepted(object? sender, EventArgs e)
	{
		if (hostnameField.Text == "")
		{
			MessageBox.ErrorQuery(null, "Error", "Please enter a hostname.", "OK");
			return;
		}
		var process = new System.Diagnostics.Process
		{
			StartInfo = new System.Diagnostics.ProcessStartInfo
			{
				FileName = "hostnamectl",
				Arguments = "set-hostname " + hostnameField.Text,
				RedirectStandardOutput = false,
				RedirectStandardError = false,
				UseShellExecute = true,
				CreateNoWindow = false,
			}
		};
		process.Start();
		process.WaitForExit();
        if (process.ExitCode != 0)
        {
			MessageBox.ErrorQuery(this.App, "Error", "Failed to set the new hostname to: " + hostnameField.Text, "OK");
        }
		this.RequestStop();
    }
}
