
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ServerManager.Dialogs {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class ChangeHostname : Terminal.Gui.Views.Dialog {
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.TextField hostnameField;
        
        private Terminal.Gui.Views.Button renameButton;
        
        private Terminal.Gui.Views.Button cancelButton;
        
        private void InitializeComponent() {
            this.cancelButton = new Terminal.Gui.Views.Button();
            this.renameButton = new Terminal.Gui.Views.Button();
            this.hostnameField = new Terminal.Gui.Views.TextField();
            this.label = new Terminal.Gui.Views.Label();
            this.Width = 90;
            this.Height = 12;
            this.X = 14;
            this.Y = 8;
            this.Visible = true;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = 2;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.CanFocus = false;
            this.label.ShadowStyle = null;
            this.label.Data = "label";
            this.label.Text = ("Enter the new name for this server.\r\n\r\nNote that you may be restart in order to a" +
                "pply correctly the name.");
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this.hostnameField.Width = 87;
            this.hostnameField.Height = 1;
            this.hostnameField.X = 0;
            this.hostnameField.Y = 5;
            this.hostnameField.Visible = true;
            this.hostnameField.CanFocus = true;
            this.hostnameField.ShadowStyle = null;
            this.hostnameField.Secret = false;
            this.hostnameField.Data = "hostnameField";
            this.hostnameField.Text = "";
            this.hostnameField.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.hostnameField);
            this.renameButton.Width = Dim.Auto();
            this.renameButton.Height = Dim.Auto();
            this.renameButton.X = 27;
            this.renameButton.Y = 7;
            this.renameButton.Visible = true;
            this.renameButton.CanFocus = true;
            this.renameButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.renameButton.Data = "renameButton";
            this.renameButton.Text = "Rename";
            this.renameButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.renameButton.IsDefault = false;
            this.Add(this.renameButton);
            this.cancelButton.Width = Dim.Auto();
            this.cancelButton.Height = Dim.Auto();
            this.cancelButton.X = 43;
            this.cancelButton.Y = 7;
            this.cancelButton.Visible = true;
            this.cancelButton.CanFocus = true;
            this.cancelButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.cancelButton.Data = "cancelButton";
            this.cancelButton.Text = "Cancel";
            this.cancelButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.cancelButton.IsDefault = false;
            this.Add(this.cancelButton);
        }
    }
}
