//------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
using Terminal.Gui;
using Terminal.Gui.Views;

namespace ServerManager.Dialogs;

public partial class InstallPackage
{
	public InstallPackage()
	{
		InitializeComponent();
		installButton.Accepted += InstallButtonAccepted;
	}

	private void InstallButtonAccepted(object? sender, EventArgs e)
	{
		if (packagesField.Text == "")
		{
			MessageBox.ErrorQuery(this.App, "Error", "Please enter a package name.", "OK");
			return;
		}
		// Create an list of packages separated by space
		var packages = packagesField.Text.ToString().Split(' ').ToList();
		var process = new System.Diagnostics.Process
		{
			StartInfo = new System.Diagnostics.ProcessStartInfo
			{
				FileName = "sudo",
				Arguments = "/usr/bin/pacman -S " + string.Join(" ", packages),
				RedirectStandardOutput = false,
				RedirectStandardError = false,
				UseShellExecute = true,
				CreateNoWindow = false,
			}
		};
		process.Start();
	}
}
