//------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
using Terminal.Gui;
using Terminal.Gui.Views;

namespace ServerManager.Dialogs;

public partial class RemovePackage
{
	public RemovePackage()
	{
		InitializeComponent();
		removeButton.Accepted += RemoveButtonAccepted;
		cancelButton.Accepted += (s, e) => this.RequestStop();
	}

	private void RemoveButtonAccepted(object? sender, EventArgs e)
	{
		if (packagesField.Text == "")
		{
			MessageBox.ErrorQuery(null, "Error", "Please enter a package name.", "OK");
			return;
		}
		// Create an list of packages separated by space
		var packages = packagesField.Text.ToString().Split(' ').ToList();
		var process = new System.Diagnostics.Process
		{
			StartInfo = new System.Diagnostics.ProcessStartInfo
			{
				FileName = "sudo",
				Arguments = "/usr/bin/pacman -R " + string.Join(" ", packages),
				UseShellExecute = true,
				CreateNoWindow = false,
			}
		};
		process.Start();
		process.WaitForExit();
		if (process.ExitCode == 0)
		{
			MessageBox.Query(null, "Success", "Package(s) removed successfully.", "OK");
		}
		else
		{
			MessageBox.ErrorQuery(null, "Error", "Failed to remove package(s).", "OK");
		}
	}
}
