
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ServerManager.Dialogs {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class RemovePackage : Terminal.Gui.Views.Dialog {
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.TextField packagesField;
        
        private Terminal.Gui.Views.Button removeButton;
        
        private Terminal.Gui.Views.Button cancelButton;
        
        private void InitializeComponent() {
            this.cancelButton = new Terminal.Gui.Views.Button();
            this.removeButton = new Terminal.Gui.Views.Button();
            this.packagesField = new Terminal.Gui.Views.TextField();
            this.label = new Terminal.Gui.Views.Label();
            this.Width = 90;
            this.Height = 12;
            this.X = 14;
            this.Y = 8;
            this.Visible = true;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Transparent;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = 2;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.CanFocus = false;
            this.label.ShadowStyle = null;
            this.label.Data = "label";
            this.label.Text = ("Enter the list of packages you want to remove on this server. Separated by spaces" +
                ".\r\n(e.g.: docker cockpit wget)\r\n\r\nPackage manager used: pacman");
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this.packagesField.Width = 87;
            this.packagesField.Height = 1;
            this.packagesField.X = 0;
            this.packagesField.Y = 5;
            this.packagesField.Visible = true;
            this.packagesField.CanFocus = true;
            this.packagesField.ShadowStyle = null;
            this.packagesField.Secret = false;
            this.packagesField.Data = "packagesField";
            this.packagesField.Text = "";
            this.packagesField.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.packagesField);
            this.removeButton.Width = Dim.Auto();
            this.removeButton.Height = Dim.Auto();
            this.removeButton.X = 27;
            this.removeButton.Y = 7;
            this.removeButton.Visible = true;
            this.removeButton.CanFocus = true;
            this.removeButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.removeButton.Data = "removeButton";
            this.removeButton.Text = "Remove";
            this.removeButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.removeButton.IsDefault = false;
            this.Add(this.removeButton);
            this.cancelButton.Width = Dim.Auto();
            this.cancelButton.Height = Dim.Auto();
            this.cancelButton.X = 43;
            this.cancelButton.Y = 7;
            this.cancelButton.Visible = true;
            this.cancelButton.CanFocus = true;
            this.cancelButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.cancelButton.Data = "cancelButton";
            this.cancelButton.Text = "Cancel";
            this.cancelButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.cancelButton.IsDefault = false;
            this.Add(this.cancelButton);
        }
    }
}
