//------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
using ServerManager.Dialogs;
using System.Diagnostics;
using Terminal.Gui;
using Terminal.Gui.App;
using Terminal.Gui.Views;

namespace ServerManager;
	
public partial class Program
{
	public Program()
	{
		InitializeComponent();
		// Getting system information
		hostnameLink.Text = Environment.MachineName;
		ufwLabel.Text = SystemInfo.GetUFWStatus();
		appArmorLabel.Text = SystemInfo.GetAppArmorStatus();
		ipLink.Text = SystemInfo.GetLocalIPAddresses();
		cpuLabel.Text = SystemInfo.GetCPU();
		ramLabel.Text = SystemInfo.GetRAM().ToString();
		storageLabel.Text = SystemInfo.GetTotalStorageBytes().ToString();
		systemdServiceCode.Text = SystemInfo.GetServices();
		// Functions to link
		installPackageButton.Accepted += InstallPackageButtonAccepted;
		removePackageButton.Accepted += RemovePackageButtonAccepted;
		servicesButton.Accepted += ServicesButtonAccepted;
		hostnameLink.Accepted += HostnameLinkAccepted;
		ipLink.Accepted += IPLinkAccepted;
	}

	public static void Main(string[] args)
	{
#pragma warning disable CS0618 // Suppress warning for obsolete Application.Run method
		Application.Run<Program>();
#pragma warning restore CS0618 // This is necessary to put because Terminal.Gui needs this to run.
	}
	#region Quick Action
	private static void InstallPackageButtonAccepted(object? sender, EventArgs e)
	{
		InstallPackage installPackage = new InstallPackage();
		Application.Run(installPackage);
	}

	private static void RemovePackageButtonAccepted(object? sender, EventArgs e)
	{
		RemovePackage removePackage = new RemovePackage();
		Application.Run(removePackage);
	}

	private static void ServicesButtonAccepted(object? sender, EventArgs e)
	{
		
	}
	#endregion
	#region System Information
	private static void HostnameLinkAccepted(object? sender, EventArgs e)
	{
		var process = new System.Diagnostics.Process
		{
			StartInfo = new System.Diagnostics.ProcessStartInfo
			{
				FileName = "hostnamectl",
				UseShellExecute = true,
				CreateNoWindow = false
			}
		};
		process.Start();
	}

	private static void IPLinkAccepted(object? sender, EventArgs e)
	{
		var process = new System.Diagnostics.Process
		{
			StartInfo = new System.Diagnostics.ProcessStartInfo
			{
				FileName = "nmtui",
				UseShellExecute = true,
				CreateNoWindow = false
			}
		};
		process.Start();
	}
	#endregion
}
