
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ServerManager {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    
    
    public partial class Program : Terminal.Gui.Views.Window {
        
        private Terminal.Gui.Views.Label blank;
        
        private Terminal.Gui.Views.Link hostnameLink;
        
        private Terminal.Gui.Views.Label blank2;
        
        private Terminal.Gui.Views.Label ufwLabel;
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.Label appArmorLabel;
        
        private Terminal.Gui.Views.Label blank3;
        
        private Terminal.Gui.Views.Link ipLink;
        
        private Terminal.Gui.Views.Label blank4;
        
        private Terminal.Gui.Views.Label cpuLabel;
        
        private Terminal.Gui.Views.Label blank5;
        
        private Terminal.Gui.Views.Label ramLabel;
        
        private Terminal.Gui.Views.Label blank6;
        
        private Terminal.Gui.Views.Label storageLabel;
        
        private Terminal.Gui.Views.Line line;
        
        private Terminal.Gui.Views.Code systemdServiceCode;
        
        private Terminal.Gui.Views.Line line2;
        
        private Terminal.Gui.Views.Code journalctlCode;
        
        private Terminal.Gui.Views.MenuBar menuBar;
        
        private Terminal.Gui.Views.MenuBarItem fileMenu;
        
        private Terminal.Gui.Views.MenuItem aboutVincentOSServerManagerMenuItem;
        
        private Terminal.Gui.Views.MenuItem exitMenuItem;
        
        private Terminal.Gui.Views.MenuBarItem quickActionMenu;
        
        private Terminal.Gui.Views.MenuItem installPackagesMenuItem;
        
        private Terminal.Gui.Views.MenuItem removePackagesMenuItem;
        
        private Terminal.Gui.Views.MenuItem manageServicesMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.Views.MenuBar();
            this.journalctlCode = new Terminal.Gui.Views.Code();
            this.line2 = new Terminal.Gui.Views.Line();
            this.systemdServiceCode = new Terminal.Gui.Views.Code();
            this.line = new Terminal.Gui.Views.Line();
            this.storageLabel = new Terminal.Gui.Views.Label();
            this.blank6 = new Terminal.Gui.Views.Label();
            this.ramLabel = new Terminal.Gui.Views.Label();
            this.blank5 = new Terminal.Gui.Views.Label();
            this.cpuLabel = new Terminal.Gui.Views.Label();
            this.blank4 = new Terminal.Gui.Views.Label();
            this.ipLink = new Terminal.Gui.Views.Link();
            this.blank3 = new Terminal.Gui.Views.Label();
            this.appArmorLabel = new Terminal.Gui.Views.Label();
            this.label = new Terminal.Gui.Views.Label();
            this.ufwLabel = new Terminal.Gui.Views.Label();
            this.blank2 = new Terminal.Gui.Views.Label();
            this.hostnameLink = new Terminal.Gui.Views.Link();
            this.blank = new Terminal.Gui.Views.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.None;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "Vincent OS Server Manager";
            this.blank.Width = Dim.Auto();
            this.blank.Height = Dim.Auto();
            this.blank.X = 2;
            this.blank.Y = 2;
            this.blank.Visible = true;
            this.blank.CanFocus = false;
            this.blank.ShadowStyle = null;
            this.blank.Data = "blank";
            this.blank.Text = "Hostname:";
            this.blank.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank);
            this.hostnameLink.Width = Dim.Auto();
            this.hostnameLink.Height = 1;
            this.hostnameLink.X = 12;
            this.hostnameLink.Y = 2;
            this.hostnameLink.Visible = true;
            this.hostnameLink.CanFocus = true;
            this.hostnameLink.ShadowStyle = null;
            this.hostnameLink.Url = "";
            this.hostnameLink.Data = "hostnameLink";
            this.hostnameLink.Text = "UI_HOSTNAME";
            this.hostnameLink.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.hostnameLink);
            this.blank2.Width = Dim.Auto();
            this.blank2.Height = Dim.Auto();
            this.blank2.X = 2;
            this.blank2.Y = 3;
            this.blank2.Visible = true;
            this.blank2.CanFocus = false;
            this.blank2.ShadowStyle = null;
            this.blank2.Data = "blank2";
            this.blank2.Text = "Firewall status:";
            this.blank2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank2);
            this.ufwLabel.Width = Dim.Auto();
            this.ufwLabel.Height = Dim.Auto();
            this.ufwLabel.X = 19;
            this.ufwLabel.Y = 3;
            this.ufwLabel.Visible = true;
            this.ufwLabel.CanFocus = false;
            this.ufwLabel.ShadowStyle = null;
            this.ufwLabel.Data = "ufwLabel";
            this.ufwLabel.Text = "UI_UFW";
            this.ufwLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.ufwLabel);
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = 2;
            this.label.Y = 4;
            this.label.Visible = true;
            this.label.CanFocus = false;
            this.label.ShadowStyle = null;
            this.label.Data = "label";
            this.label.Text = "AppArmor status:";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this.appArmorLabel.Width = Dim.Auto();
            this.appArmorLabel.Height = Dim.Auto();
            this.appArmorLabel.X = 19;
            this.appArmorLabel.Y = 4;
            this.appArmorLabel.Visible = true;
            this.appArmorLabel.CanFocus = false;
            this.appArmorLabel.ShadowStyle = null;
            this.appArmorLabel.Data = "appArmorLabel";
            this.appArmorLabel.Text = "UI_APPARMOR";
            this.appArmorLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.appArmorLabel);
            this.blank3.Width = Dim.Auto();
            this.blank3.Height = Dim.Auto();
            this.blank3.X = 2;
            this.blank3.Y = 5;
            this.blank3.Visible = true;
            this.blank3.CanFocus = false;
            this.blank3.ShadowStyle = null;
            this.blank3.Data = "blank3";
            this.blank3.Text = "IP Addresses:";
            this.blank3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank3);
            this.ipLink.Width = Dim.Auto();
            this.ipLink.Height = Dim.Auto();
            this.ipLink.X = 16;
            this.ipLink.Y = 5;
            this.ipLink.Visible = true;
            this.ipLink.CanFocus = true;
            this.ipLink.ShadowStyle = null;
            this.ipLink.Url = "";
            this.ipLink.Data = "ipLink";
            this.ipLink.Text = "UI_IPADDRESSES";
            this.ipLink.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.ipLink);
            this.blank4.Width = Dim.Auto();
            this.blank4.Height = Dim.Auto();
            this.blank4.X = 2;
            this.blank4.Y = 6;
            this.blank4.Visible = true;
            this.blank4.CanFocus = false;
            this.blank4.ShadowStyle = null;
            this.blank4.Data = "blank4";
            this.blank4.Text = "Processor:";
            this.blank4.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank4);
            this.cpuLabel.Width = Dim.Auto();
            this.cpuLabel.Height = Dim.Auto();
            this.cpuLabel.X = 13;
            this.cpuLabel.Y = 6;
            this.cpuLabel.Visible = true;
            this.cpuLabel.CanFocus = false;
            this.cpuLabel.ShadowStyle = null;
            this.cpuLabel.Data = "cpuLabel";
            this.cpuLabel.Text = "UI_CPU";
            this.cpuLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.cpuLabel);
            this.blank5.Width = Dim.Auto();
            this.blank5.Height = Dim.Auto();
            this.blank5.X = 2;
            this.blank5.Y = 7;
            this.blank5.Visible = true;
            this.blank5.CanFocus = false;
            this.blank5.ShadowStyle = null;
            this.blank5.Data = "blank5";
            this.blank5.Text = "Memory (RAM):";
            this.blank5.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank5);
            this.ramLabel.Width = Dim.Auto();
            this.ramLabel.Height = Dim.Auto();
            this.ramLabel.X = 16;
            this.ramLabel.Y = 7;
            this.ramLabel.Visible = true;
            this.ramLabel.CanFocus = false;
            this.ramLabel.ShadowStyle = null;
            this.ramLabel.Data = "ramLabel";
            this.ramLabel.Text = "UI_RAM";
            this.ramLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.ramLabel);
            this.blank6.Width = Dim.Auto();
            this.blank6.Height = Dim.Auto();
            this.blank6.X = 2;
            this.blank6.Y = 8;
            this.blank6.Visible = true;
            this.blank6.CanFocus = false;
            this.blank6.ShadowStyle = null;
            this.blank6.Data = "blank6";
            this.blank6.Text = "Total storage:";
            this.blank6.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank6);
            this.storageLabel.Width = Dim.Auto();
            this.storageLabel.Height = Dim.Auto();
            this.storageLabel.X = 17;
            this.storageLabel.Y = 8;
            this.storageLabel.Visible = true;
            this.storageLabel.CanFocus = false;
            this.storageLabel.ShadowStyle = null;
            this.storageLabel.Data = "storageLabel";
            this.storageLabel.Text = "UI_STORAGE";
            this.storageLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.storageLabel);
            this.line.Width = Dim.Fill(0);
            this.line.Height = 1;
            this.line.X = 0;
            this.line.Y = 10;
            this.line.Visible = true;
            this.line.CanFocus = false;
            this.line.ShadowStyle = null;
            this.line.Data = "line";
            this.line.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.line.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.Add(this.line);
            this.systemdServiceCode.Width = Dim.Auto();
            this.systemdServiceCode.Height = Dim.Auto();
            this.systemdServiceCode.X = 0;
            this.systemdServiceCode.Y = 11;
            this.systemdServiceCode.Visible = true;
            this.systemdServiceCode.CanFocus = false;
            this.systemdServiceCode.ShadowStyle = null;
            this.systemdServiceCode.Data = "systemdServiceCode";
            this.systemdServiceCode.Text = "";
            this.systemdServiceCode.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.systemdServiceCode);
            this.line2.Width = Dim.Fill(0);
            this.line2.Height = 1;
            this.line2.X = -1;
            this.line2.Y = 19;
            this.line2.Visible = true;
            this.line2.CanFocus = false;
            this.line2.ShadowStyle = null;
            this.line2.Data = "line2";
            this.line2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.line2.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.Add(this.line2);
            this.journalctlCode.Width = Dim.Auto();
            this.journalctlCode.Height = Dim.Auto();
            this.journalctlCode.X = 0;
            this.journalctlCode.Y = 20;
            this.journalctlCode.Visible = true;
            this.journalctlCode.CanFocus = false;
            this.journalctlCode.ShadowStyle = null;
            this.journalctlCode.Data = "journalctlCode";
            this.journalctlCode.Text = "";
            this.journalctlCode.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.journalctlCode);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = Dim.Auto();
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.CanFocus = false;
            this.menuBar.ShadowStyle = null;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.fileMenu = new Terminal.Gui.Views.MenuBarItem();
            this.fileMenu.Title = "_File";
            this.fileMenu.Key = new Key("F9");
            this.aboutVincentOSServerManagerMenuItem = new Terminal.Gui.Views.MenuItem();
            this.aboutVincentOSServerManagerMenuItem.Title = "About Vincent OS Server Manager";
            this.aboutVincentOSServerManagerMenuItem.Action = () =>
			{
				MessageBox.Query(this.App, "About Vincent OS Server Manager", "Server Manager\nVersion: 1.0.0\nAuthor: v38armageddon", "OK");
			};
            this.exitMenuItem = new Terminal.Gui.Views.MenuItem();
            this.exitMenuItem.Title = "Exit";
            this.exitMenuItem.Key = new Key("Esc");
            this.exitMenuItem.Action = () =>
            {
				Application.RequestStop();
			};
            this.fileMenu.PopoverMenu = new PopoverMenu([aboutVincentOSServerManagerMenuItem,exitMenuItem]);
            this.menuBar.Add(this.fileMenu);
            this.quickActionMenu = new Terminal.Gui.Views.MenuBarItem();
            this.quickActionMenu.Title = "Quick Action";
            this.quickActionMenu.Key = new Key("F10");
            this.installPackagesMenuItem = new Terminal.Gui.Views.MenuItem();
            this.installPackagesMenuItem.Title = "Install packages";
            this.installPackagesMenuItem.Action = () =>
            {
                InstallPackageButtonAccepted(this.installPackagesMenuItem, EventArgs.Empty);
			};
            this.removePackagesMenuItem = new Terminal.Gui.Views.MenuItem();
            this.removePackagesMenuItem.Title = "Remove packages";
            this.removePackagesMenuItem.Action = () =>
            {
                RemovePackageButtonAccepted(this.removePackagesMenuItem, EventArgs.Empty);
            };
            this.manageServicesMenuItem = new Terminal.Gui.Views.MenuItem();
            this.manageServicesMenuItem.Title = "Manage services";
            this.manageServicesMenuItem.Action = () =>
            {
                ServicesButtonAccepted(this.manageServicesMenuItem, EventArgs.Empty);
            };
            this.quickActionMenu.PopoverMenu = new PopoverMenu([installPackagesMenuItem,removePackagesMenuItem,manageServicesMenuItem]);
            this.menuBar.Add(this.quickActionMenu);
            this.Add(this.menuBar);
        }
    }
}
