
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace ServerManager {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Program : Terminal.Gui.Views.Window {
        
        private Terminal.Gui.Views.FrameView quickActionView;
        
        private Terminal.Gui.Views.Button installPackageButton;
        
        private Terminal.Gui.Views.Button removePackageButton;
        
        private Terminal.Gui.Views.Button servicesButton;
        
        private Terminal.Gui.Views.Label blank;
        
        private Terminal.Gui.Views.Link hostnameLink;
        
        private Terminal.Gui.Views.Label blank2;
        
        private Terminal.Gui.Views.Label ufwLabel;
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.Label appArmorLabel;
        
        private Terminal.Gui.Views.Label blank3;
        
        private Terminal.Gui.Views.Label ipLabel;
        
        private Terminal.Gui.Views.Label blank4;
        
        private Terminal.Gui.Views.Label cpuLabel;
        
        private Terminal.Gui.Views.Label blank5;
        
        private Terminal.Gui.Views.Label ramLabel;
        
        private Terminal.Gui.Views.Label blank6;
        
        private Terminal.Gui.Views.Label storageLabel;
        
        private Terminal.Gui.Views.Line line;
        
        private Terminal.Gui.Views.Line line2;
        
        private void InitializeComponent() {
            this.line2 = new Terminal.Gui.Views.Line();
            this.line = new Terminal.Gui.Views.Line();
            this.storageLabel = new Terminal.Gui.Views.Label();
            this.blank6 = new Terminal.Gui.Views.Label();
            this.ramLabel = new Terminal.Gui.Views.Label();
            this.blank5 = new Terminal.Gui.Views.Label();
            this.cpuLabel = new Terminal.Gui.Views.Label();
            this.blank4 = new Terminal.Gui.Views.Label();
            this.ipLabel = new Terminal.Gui.Views.Label();
            this.blank3 = new Terminal.Gui.Views.Label();
            this.appArmorLabel = new Terminal.Gui.Views.Label();
            this.label = new Terminal.Gui.Views.Label();
            this.ufwLabel = new Terminal.Gui.Views.Label();
            this.blank2 = new Terminal.Gui.Views.Label();
            this.hostnameLink = new Terminal.Gui.Views.Link();
            this.blank = new Terminal.Gui.Views.Label();
            this.servicesButton = new Terminal.Gui.Views.Button();
            this.removePackageButton = new Terminal.Gui.Views.Button();
            this.installPackageButton = new Terminal.Gui.Views.Button();
            this.quickActionView = new Terminal.Gui.Views.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.None;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "Vincent OS Server Manager";
            this.quickActionView.Width = 30;
            this.quickActionView.Height = 10;
            this.quickActionView.X = 88;
            this.quickActionView.Y = 0;
            this.quickActionView.Visible = true;
            this.quickActionView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.quickActionView.CanFocus = true;
            this.quickActionView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.None;
            this.quickActionView.Data = "quickActionView";
            this.quickActionView.TextAlignment = Terminal.Gui.ViewBase.Alignment.End;
            this.quickActionView.Title = "Quick actions";
            this.Add(this.quickActionView);
            this.installPackageButton.Width = Dim.Auto();
            this.installPackageButton.Height = Dim.Auto();
            this.installPackageButton.X = 1;
            this.installPackageButton.Y = 1;
            this.installPackageButton.Visible = true;
            this.installPackageButton.CanFocus = true;
            this.installPackageButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.installPackageButton.Data = "installPackageButton";
            this.installPackageButton.Text = "Install packages";
            this.installPackageButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.installPackageButton.IsDefault = false;
            this.quickActionView.Add(this.installPackageButton);
            this.removePackageButton.Width = Dim.Auto();
            this.removePackageButton.Height = Dim.Auto();
            this.removePackageButton.X = 1;
            this.removePackageButton.Y = 3;
            this.removePackageButton.Visible = true;
            this.removePackageButton.CanFocus = true;
            this.removePackageButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.removePackageButton.Data = "removePackageButton";
            this.removePackageButton.Text = "Remove packages";
            this.removePackageButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.removePackageButton.IsDefault = false;
            this.quickActionView.Add(this.removePackageButton);
            this.servicesButton.Width = Dim.Auto();
            this.servicesButton.Height = Dim.Auto();
            this.servicesButton.X = 1;
            this.servicesButton.Y = 5;
            this.servicesButton.Visible = true;
            this.servicesButton.CanFocus = true;
            this.servicesButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.servicesButton.Data = "servicesButton";
            this.servicesButton.Text = "Manage services";
            this.servicesButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.servicesButton.IsDefault = false;
            this.quickActionView.Add(this.servicesButton);
            this.blank.Width = Dim.Auto();
            this.blank.Height = Dim.Auto();
            this.blank.X = 2;
            this.blank.Y = 1;
            this.blank.Visible = true;
            this.blank.CanFocus = false;
            this.blank.ShadowStyle = null;
            this.blank.Data = "blank";
            this.blank.Text = "Hostname:";
            this.blank.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank);
            this.hostnameLink.Width = 19;
            this.hostnameLink.Height = 1;
            this.hostnameLink.X = 12;
            this.hostnameLink.Y = 1;
            this.hostnameLink.Visible = true;
            this.hostnameLink.CanFocus = true;
            this.hostnameLink.ShadowStyle = null;
            this.hostnameLink.Url = "";
            this.hostnameLink.Data = "hostnameLink";
            this.hostnameLink.Text = "UI_HOSTNAME";
            this.hostnameLink.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.hostnameLink);
            this.blank2.Width = Dim.Auto();
            this.blank2.Height = Dim.Auto();
            this.blank2.X = 2;
            this.blank2.Y = 2;
            this.blank2.Visible = true;
            this.blank2.CanFocus = false;
            this.blank2.ShadowStyle = null;
            this.blank2.Data = "blank2";
            this.blank2.Text = "Firewall status:";
            this.blank2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank2);
            this.ufwLabel.Width = Dim.Auto();
            this.ufwLabel.Height = Dim.Auto();
            this.ufwLabel.X = 19;
            this.ufwLabel.Y = 2;
            this.ufwLabel.Visible = true;
            this.ufwLabel.CanFocus = false;
            this.ufwLabel.ShadowStyle = null;
            this.ufwLabel.Data = "ufwLabel";
            this.ufwLabel.Text = "UI_UFW";
            this.ufwLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.ufwLabel);
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = 2;
            this.label.Y = 3;
            this.label.Visible = true;
            this.label.CanFocus = false;
            this.label.ShadowStyle = null;
            this.label.Data = "label";
            this.label.Text = "AppArmor status:";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this.appArmorLabel.Width = Dim.Auto();
            this.appArmorLabel.Height = Dim.Auto();
            this.appArmorLabel.X = 19;
            this.appArmorLabel.Y = 3;
            this.appArmorLabel.Visible = true;
            this.appArmorLabel.CanFocus = false;
            this.appArmorLabel.ShadowStyle = null;
            this.appArmorLabel.Data = "appArmorLabel";
            this.appArmorLabel.Text = "UI_APPARMOR";
            this.appArmorLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.appArmorLabel);
            this.blank3.Width = Dim.Auto();
            this.blank3.Height = Dim.Auto();
            this.blank3.X = 2;
            this.blank3.Y = 4;
            this.blank3.Visible = true;
            this.blank3.CanFocus = false;
            this.blank3.ShadowStyle = null;
            this.blank3.Data = "blank3";
            this.blank3.Text = "IP Addresses:";
            this.blank3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank3);
            this.ipLabel.Width = Dim.Auto();
            this.ipLabel.Height = Dim.Auto();
            this.ipLabel.X = 16;
            this.ipLabel.Y = 4;
            this.ipLabel.Visible = true;
            this.ipLabel.CanFocus = false;
            this.ipLabel.ShadowStyle = null;
            this.ipLabel.Data = "ipLabel";
            this.ipLabel.Text = "UI_IPADDRESSES";
            this.ipLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.ipLabel);
            this.blank4.Width = Dim.Auto();
            this.blank4.Height = Dim.Auto();
            this.blank4.X = 2;
            this.blank4.Y = 5;
            this.blank4.Visible = true;
            this.blank4.CanFocus = false;
            this.blank4.ShadowStyle = null;
            this.blank4.Data = "blank4";
            this.blank4.Text = "Processor:";
            this.blank4.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank4);
            this.cpuLabel.Width = Dim.Auto();
            this.cpuLabel.Height = Dim.Auto();
            this.cpuLabel.X = 13;
            this.cpuLabel.Y = 5;
            this.cpuLabel.Visible = true;
            this.cpuLabel.CanFocus = false;
            this.cpuLabel.ShadowStyle = null;
            this.cpuLabel.Data = "cpuLabel";
            this.cpuLabel.Text = "UI_CPU";
            this.cpuLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.cpuLabel);
            this.blank5.Width = Dim.Auto();
            this.blank5.Height = Dim.Auto();
            this.blank5.X = 2;
            this.blank5.Y = 6;
            this.blank5.Visible = true;
            this.blank5.CanFocus = false;
            this.blank5.ShadowStyle = null;
            this.blank5.Data = "blank5";
            this.blank5.Text = "Memory (RAM):";
            this.blank5.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank5);
            this.ramLabel.Width = Dim.Auto();
            this.ramLabel.Height = Dim.Auto();
            this.ramLabel.X = 16;
            this.ramLabel.Y = 6;
            this.ramLabel.Visible = true;
            this.ramLabel.CanFocus = false;
            this.ramLabel.ShadowStyle = null;
            this.ramLabel.Data = "ramLabel";
            this.ramLabel.Text = "UI_RAM";
            this.ramLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.ramLabel);
            this.blank6.Width = Dim.Auto();
            this.blank6.Height = Dim.Auto();
            this.blank6.X = 2;
            this.blank6.Y = 7;
            this.blank6.Visible = true;
            this.blank6.CanFocus = false;
            this.blank6.ShadowStyle = null;
            this.blank6.Data = "blank6";
            this.blank6.Text = "Total storage:";
            this.blank6.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.blank6);
            this.storageLabel.Width = Dim.Auto();
            this.storageLabel.Height = Dim.Auto();
            this.storageLabel.X = 17;
            this.storageLabel.Y = 7;
            this.storageLabel.Visible = true;
            this.storageLabel.CanFocus = false;
            this.storageLabel.ShadowStyle = null;
            this.storageLabel.Data = "storageLabel";
            this.storageLabel.Text = "UI_STORAGE";
            this.storageLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.storageLabel);
            this.line.Width = Dim.Fill(0);
            this.line.Height = 1;
            this.line.X = -1;
            this.line.Y = 16;
            this.line.Visible = true;
            this.line.CanFocus = false;
            this.line.ShadowStyle = null;
            this.line.Data = "line";
            this.line.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.line.Orientation = Terminal.Gui.ViewBase.Orientation.Horizontal;
            this.Add(this.line);
            this.line2.Width = 1;
            this.line2.Height = Dim.Fill(0);
            this.line2.X = 61;
            this.line2.Y = 16;
            this.line2.Visible = true;
            this.line2.CanFocus = false;
            this.line2.ShadowStyle = null;
            this.line2.Data = "line2";
            this.line2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.line2.Orientation = Terminal.Gui.ViewBase.Orientation.Vertical;
            this.Add(this.line2);
        }
    }
}
