//------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// ----------------------------------------------------------------------------- 
#pragma warning disable CS0618 // This is necessary to put because Terminal.Gui needs this to run.
using ServerManager.Dialogs;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Terminal.Gui;
using Terminal.Gui.App;
using Terminal.Gui.Input;
using Terminal.Gui.Views;

namespace ServerManager;

public partial class Program
{
	public Program()
	{
		InitializeComponent();
		// Getting system information
		hostnameLink.Text = Environment.MachineName;
		ufwLabel.Text = SystemInfo.GetUFWStatus();
		appArmorLabel.Text = SystemInfo.GetAppArmorStatus();
		ipLink.Text = SystemInfo.GetLocalIPAddresses();
		cpuLabel.Text = SystemInfo.GetCPU();
		ramLabel.Text = SystemInfo.GetRAM().ToString();
		storageLabel.Text = SystemInfo.GetTotalStorageBytes().ToString();
		systemdServiceCode.Text = SystemInfo.GetServices();
		journalctlCode.Text = SystemInfo.GetSystemLogs();
		// Functions to link
		hostnameLink.Accepted += HostnameLinkAccepted;
		ipLink.Accepted += IPLinkAccepted;
	}

	public static void Main(string[] args)
	{
		Application.Run<Program>();
	}

	#region Quick Action
	private void InstallPackageButtonAccepted(object? sender, EventArgs e)
	{
		InstallPackage installPackage = new InstallPackage();
		Application.Run(installPackage);
	}

	private void RemovePackageButtonAccepted(object? sender, EventArgs e)
	{
		RemovePackage removePackage = new RemovePackage();
		Application.Run(removePackage);
	}

	private void ServicesButtonAccepted(object? sender, EventArgs e)
	{
		MessageBox.Query(this.App, "TITLE", "Not implemented", "OK");
	}
	#endregion
	#region System Information
	private void HostnameLinkAccepted(object? sender, EventArgs e)
	{
		ChangeHostname changeHostname = new ChangeHostname();
		Application.Run(changeHostname);
	}

	private void IPLinkAccepted(object? sender, EventArgs e)
	{
		try
		{
			var process = new System.Diagnostics.Process
			{
				StartInfo = new System.Diagnostics.ProcessStartInfo
				{
					FileName = "nmtui",
					UseShellExecute = false,
					CreateNoWindow = false
				}
			};
			process.Start();
			process.WaitForExit();
		}
		catch (Exception ex)
		{
			MessageBox.ErrorQuery(this.App, "Error", $"{ex.Message}", "OK");
		}
	}
	#endregion
}
