//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
using Terminal.Gui;
using Terminal.Gui.App;

namespace ServerManager;
	
public partial class Program
{
	public Program()
	{
		InitializeComponent();
		hostnameLabel.Text = Environment.MachineName;
        ufwLabel.Text = SystemInfo.GetUFWStatus();
        ipLabel.Text = SystemInfo.GetLocalIPAddresses();
        cpuLabel.Text = SystemInfo.GetCPU();
        ramLabel.Text = SystemInfo.GetRAM().ToString();
        storageLabel.Text = SystemInfo.GetTotalStorageBytes().ToString();
    }

	public static void Main(string[] args)
	{
		Application.Run<Program>();
	}
}
